// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJKSel2fjNUHIhc2s3_DKkF16BJJNmizI',
    appId: '1:146446211964:web:abada2c10f2ff0157d62f9',
    messagingSenderId: '146446211964',
    projectId: 'uniservice-e924d',
    authDomain: 'uniservice-e924d.firebaseapp.com',
    storageBucket: 'uniservice-e924d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZGFvZna_QIsLrccI6LxYMGXXDP03fsDg',
    appId: '1:146446211964:android:308113c12121dbc47d62f9',
    messagingSenderId: '146446211964',
    projectId: 'uniservice-e924d',
    storageBucket: 'uniservice-e924d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH90ycKvSGEKMFNCZhXiIvehGqD9HggEc',
    appId: '1:146446211964:ios:08f8bdc1f2e8c9567d62f9',
    messagingSenderId: '146446211964',
    projectId: 'uniservice-e924d',
    storageBucket: 'uniservice-e924d.firebasestorage.app',
    iosClientId: '146446211964-d28k1ejra51sphjsa3t2qptun7o9irap.apps.googleusercontent.com',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH90ycKvSGEKMFNCZhXiIvehGqD9HggEc',
    appId: '1:146446211964:ios:08f8bdc1f2e8c9567d62f9',
    messagingSenderId: '146446211964',
    projectId: 'uniservice-e924d',
    storageBucket: 'uniservice-e924d.firebasestorage.app',
    iosClientId: '146446211964-d28k1ejra51sphjsa3t2qptun7o9irap.apps.googleusercontent.com',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJKSel2fjNUHIhc2s3_DKkF16BJJNmizI',
    appId: '1:146446211964:web:2912849b6452158b7d62f9',
    messagingSenderId: '146446211964',
    projectId: 'uniservice-e924d',
    authDomain: 'uniservice-e924d.firebaseapp.com',
    storageBucket: 'uniservice-e924d.firebasestorage.app',
  );
}
